# Calcul matriciel : Opérations élémentaires

Soient les matrices $M=\begin{pmatrix}4&1&6&-9\\
0&10&4&-1\\
-3&0&1&1\\
1&4&6&0\\
\end{pmatrix}$ et $N=\begin{pmatrix}1&0&6&-6\\
0&3&2&1\\
-3&0&1&1\\
7&1&6&1\\
\end{pmatrix}$.

Dans ce paragraphe, une matrices est representée par une liste des liste. Par exemple les matrices $M$ et $N$ seront représentées par :

M = [ [4, 1, 6, -9], [0, 10, 4, -1], [-3, 0, 1, 1], [1, 4, 6,0] ] et N = [ [1, 0, 6, -6], [0, 3, 2, 1], [-3, 0, 1, 1], [7, 1, 6, 1] ] 

## Somme, produit de deux matrices  et produit d'une matrice par un scalaire

### Somme, produit de deux matrices et produit d'une matrice par un scalaire sans numpy

In [1]:
def somme(M, N): 
        n=len(M) # nombre de lignes 
        m=len(M[0]) # nombre de colonnes 
        return [[M[i][j] + N[i][j] for j in range(m)] for i in range(n)]
M = [ [4, 1, 6, -9], [0, 10, 4, -1], [-3, 0, 1, 1], [1, 4, 6, 0] ] 
N = [ [1, 0, 6, -6], [0, 3, 2, 1], [-3, 0, 1, 1], [7, 1, 6, 1] ] 
print("M + N = : ", somme(M, N)) # affiche la somme des matrcies M et N


M + N = :  [[5, 1, 12, -15], [0, 13, 6, 0], [-6, 0, 2, 2], [8, 5, 12, 1]]


In [2]:
def produit(M, N):
        return [[sum(L[k] * N[k][j] for k in range(len(L))) for j in range(len(N[0]))] for L in M]
print("MN =",produit(M,N)) # affiche le produit des matrices M et N

MN = [[-77, -6, -22, -26], [-19, 29, 18, 13], [1, 1, -11, 20], [-17, 12, 20, 4]]


In [3]:
def prod(a,N) :
    N = [[1, 0, 6, -6], [0, 3, 2, 1], [-3, 0, 1, 1], [7, 1, 6, 1] ] 
    n=len(N) #nombre de lignes
    m=len(N[0]) # nombre de colonnes
    return [[a*N[i][j] for j in range(m)] for i in range(n)]
print("3N = ", prod(3,N)) #affiche le produit de N par 3
print("0N = ", prod(0,N)) #affiche le produit de N par 0

3N =  [[3, 0, 18, -18], [0, 9, 6, 3], [-9, 0, 3, 3], [21, 3, 18, 3]]
0N =  [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


### Somme, produit de deux matrices et produit d'une matrice par un scalaire avec numpy

In [4]:
import numpy as np 
M = np.array([ [4, 1, 6, -9], [0, 10, 4, -1], [-3, 0, 1, 1], [1, 4, 6, 0]])
N = np.array([ [1, 0, 6, -6], [0, 3, 2, 1], [-3, 0, 1, 1], [7, 1, 6, 1] ])
C= M + N
D= M*N
E=3*N
print("M+N=",C)
print("MN=",D)
print("3N=",E)

M+N= [[  5   1  12 -15]
 [  0  13   6   0]
 [ -6   0   2   2]
 [  8   5  12   1]]
MN= [[ 4  0 36 54]
 [ 0 30  8 -1]
 [ 9  0  1  1]
 [ 7  4 36  0]]
3N= [[  3   0  18 -18]
 [  0   9   6   3]
 [ -9   0   3   3]
 [ 21   3  18   3]]


## Transposée d’une matrice

Soit la matrice $A=\begin{pmatrix}2&3&2&8&5\\
1&10&5&3&2\\
1&13&3&3&1\\
2&4&6&1&14\\
\end{pmatrix}$

### Transposée d’une matrice sans numpy

In [5]:
def trans(A):
        return[[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]
A=[[2, 3, 2, 8, 5], [1, 10, 5, 3, 2], [1, 13, 3, 3, 1], [2, 4, 6, 1, 14] ] 
trans(A) # affiche la transposée de la matrice A

[[2, 1, 1, 2], [3, 10, 13, 4], [2, 5, 3, 6], [8, 3, 3, 1], [5, 2, 1, 14]]

### Transposée d’une matrice avec numpy

In [6]:
import numpy as np
A = np.array([[2, 3, 2, 8, 5], [1, 10, 5, 3, 2], [1, 13, 3, 3, 1], [2, 4, 6, 1, 14]])
print(A.transpose()) #affiche la transposée de la matrice A

[[ 2  1  1  2]
 [ 3 10 13  4]
 [ 2  5  3  6]
 [ 8  3  3  1]
 [ 5  2  1 14]]


## Les opération élémentaires sur les lignes 

### L'opération $l_i\leftarrow l_j$

In [7]:
def echange_lignes(M, i, j):
        M[i], M[j] = M[j], M[i] 
        return M 
M=M=[[1, -6, 4, 5, 2], [3, 2, 0, 2, 8], [5, 6, 7, -11, 5]]
echange_lignes(M, 0, 1) # echanger la ligne 1 avec la ligne 2

[[3, 2, 0, 2, 8], [1, -6, 4, 5, 2], [5, 6, 7, -11, 5]]

### L'opération élémentaire  $l_i\leftarrow \lambda l_i$

In [8]:
def multip_ligne(M, i, λ): 
        M[i] = [coeff * λ for coeff in M[i]] 
        return M 
M=[[1, -6, 4, 5, 2], [3, 2, 0, 2, 8], [5, 6, 7, -11, 5]] 
print(M) #affiche la matrice M
multip_ligne(M, 0, 6) #remplacer la ligne 1 par son produit par 6 

[[1, -6, 4, 5, 2], [3, 2, 0, 2, 8], [5, 6, 7, -11, 5]]


[[6, -36, 24, 30, 12], [3, 2, 0, 2, 8], [5, 6, 7, -11, 5]]

### L'opération élémentaire $l_i\leftarrow l_i+\lambda l_j$

In [9]:
def transvection(M, i, j, λ): 
        M[i] = [M[i][k] + λ * M[j][k] for k in range(len(M[i]))] 
        return M 
M=[[1, -6, 4, 5, 2], [3, 2, 0, 2, 8], [5, 6, 7, -11, 5]] 
transvection(M, 1, 2, 8) #remplacer la ligne 2 par la somme de la ligne 2 et la ligne 3 multipliée par 8

[[1, -6, 4, 5, 2], [43, 50, 56, -86, 48], [5, 6, 7, -11, 5]]